language: java

jdk:
  - oraclejdk8

script: mvn --settings ./settings.xml clean verify

deploy:
  - provider: script
    script: ./deploy.sh
    skip_cleanup: true
    on:
      repo: flux-capacitor-io/flux-capacitor-client
      tags: true
      jdk: oraclejdk8


notifications:
  email:
    - admin@flux-capacitor.io